"""naming

Revision ID: 23a73509de38
Revises: f3879f831dee
Create Date: 2019-11-26 23:50:21.760734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a73509de38'
down_revision = 'f3879f831dee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whisper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whisper_timestamp'), 'whisper', ['timestamp'], unique=False)
    op.drop_index('ix_whispers_timestamp', table_name='whispers')
    op.drop_table('whispers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whispers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_whispers_timestamp', 'whispers', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_whisper_timestamp'), table_name='whisper')
    op.drop_table('whisper')
    # ### end Alembic commands ###
