"""adding a created time

Revision ID: 6d911f4a1072
Revises: fc915266424c
Create Date: 2019-11-27 04:07:25.450470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d911f4a1072'
down_revision = 'fc915266424c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_created'), 'user', ['created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_created'), table_name='user')
    op.drop_column('user', 'created')
    # ### end Alembic commands ###
